database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: spurs

  # the password
  password: spurs

  # the JDBC URL
  url: jdbc:h2:./db/banking

  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

server:
  rootPath: /banking/
  applicationConnectors:
    - type: http
      port: 7100
  adminConnectors:
    - type: http
      port: 7101

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.speedingplanet: DEBUG

    # Redirects SQL logs to a separate file
    org.hibernate.SQL: DEBUG
